# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 276b36548166a52f793095e1903d48113555dfc228434ca5aa54e47cfb4af1f38b4aa8fe8eac2d21e35e3299689d42dcaf1ab80a5238deae16ef1bb6239d7024

test:
  secret_key_base: 6cbcb833998eeed9917f913aa876024eb3cff288212f894aa944ae5c17ed35df8014f0d105506a8995a5365849b1291d7132097b676b8b1fc9175f3f932c8731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
